baseURL = "https://starlingsintheslipstream.com/"
languageCode = "en-us"
title = "Starlings in the Slipstream"
theme = "archie"
copyright = "© Starlings in the Slipstream"

# Enable tags
[taxonomies]
   tag = "tags"

[params]
  mode = "auto"
  useCDN = true
  subtitle = "A music blog"

# Social media links
[params.social]
  github = "your-github-username" # Optional: Add your GitHub username if you want to link to it
