baseURL = 'https://starlingsoftheslipstream.com/'
languageCode = 'en-us'
title = 'Starlings in the Slipstream'

# Theme settings
theme = 'PaperMod'

# Site settings
pagination.pagerSize = 5
defaultContentLanguage = 'en'

[params]
  # Theme parameters
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
[menu]
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 20
