baseURL = 'https://starlingsintheslipstream.com/'
languageCode = 'en-us'
title = 'Starlings in the Slipstream'
copyright = '© Starlings in the Slipstream'

# Theme settings
theme = 'archie'

# Enable tags
[taxonomies]
  tag = 'tags'

# Site settings
defaultContentLanguage = 'en'

# Allow HTML in markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  mode = 'auto'
  useCDN = true
  subtitle = 'A music blog'
  # Custom CSS
  customCSS = ['css/custom.css']
  # Theme parameters
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

# Social media links
[params.social]
  github = 'your-github-username' # Optional: Add your GitHub username if you want to link to it
  # Home page settings
  mainSections = ["posts"]
  showAllPostsOnHomePage = true
  showAllPostsArchive = true
  showFullTextinMainSection = true
  enableInlineShortcodes = true

  # List view settings
  [params.list]
    showFullContent = true
    disableSpecial1stPost = true
  
[menu]
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 20
