baseURL = 'https://starlingsoftheslipstream.com/'
languageCode = 'en-us'
title = 'Starlings in the Slipstream'

# Theme settings
theme = 'PaperMod'

# Site settings
defaultContentLanguage = 'en'

# Pagination
pagerSize = 5
pagination.path = "page"

# Allow HTML in markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # Theme parameters
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  # Home page settings
  mainSections = ["posts"]
  showAllPostsOnHomePage = true
  showAllPostsArchive = true
  showFullTextinMainSection = true # Show full blog post content

  # List view settings
  [params.list]
    showFullContent = true
    disableSpecial1stPost = true
  
[menu]
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 20
